language: android

jdk:
    - oraclejdk7

android:
    components:
        - android-23
        - build-tools-23.0.2

sudo: false

script: ./gradlew build

notifications:
    email: false

cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle

