language: android

jdk:
    - oraclejdk7

android:
    components:
        - tools
        - android-23
        - build-tools-23.0.2
        - extra-google-m2repository
        - extra-android-m2repository

sudo: false

script: ./gradlew test --stacktrace

notifications:
    email: false

cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle

